#!/bin/bash

echo " "
echo " 88888888ba,                88           88                                  88      88  "
echo " 88      \`\"8b               88           \"\"                                ,d88    ,d88  "
echo " 88        \`8b              88                                           888888  888888  "
echo " 88         88   ,adPPYba,  88,dPPYba,   88  ,adPPYYba,  8b,dPPYba,          88      88  "
echo " 88         88  a8P_____88  88P'    \"8a  88  \"\"     \`Y8  88P'   \`\"8a         88      88  "
echo " 88         8P  8PP\"\"\"\"\"\"\"  88       d8  88  ,adPPPPP88  88       88         88      88  "
echo " 88      .a8P   \"8b,   ,aa  88b,   ,a8\"  88  88,    ,88  88       88         88      88  "
echo " 88888888Y\"'     \`\"Ybbd8\"'  8Y\"Ybbd8\"'   88  \`\"8bbdP\"Y8  88       88         88      88  "
echo " "
