#!/bin/bash

upSeconds="$(/usr/bin/cut -d. -f1 /proc/uptime)"
secs=$((${upSeconds}%60))
mins=$((${upSeconds}/60%60))
hours=$((${upSeconds}/3600%24))
days=$((${upSeconds}/86400))
UPTIME=`printf "%d day(s) %02dh %02dm %02ds" "$days" "$hours" "$mins" "$secs"`
MEM_USED=`cat /proc/meminfo | grep Active: | awk {'print ($2/1024)'}`
MEM_FREE=`cat /proc/meminfo | grep MemAvailable | awk {'print ($2/1024)'}`
MEM_TOTAL=`cat /proc/meminfo | grep MemTotal | awk {'print ($2/1024)'}`
IP_LOCAL=`ip a | grep glo | awk '{print $2}' | head -1 | cut -f1 -d/`
IP_EXTERNAL=`wget -q -O - http://icanhazip.com/ | tail`
WEATHER_AMBARES=`curl -s "http://rss.accuweather.com/rss/liveweather_rss.asp?metric=1&locCode=EUR|FR|GIRONDE|AMBARES-ET-LAGRAVE" | sed -n '/Currently:/ s/.*: \(.*\): \([0-9]*\)\([CF]\).*/\2°\3, \1/p'`


# get the load averages
read one five fifteen rest < /proc/loadavg

# Display the MotD
echo " "
echo "Today is `date +"%A, %e %B %Y, %r"`"
echo " "
echo " Memory             : ${MEM_USED} MB (User) ${MEM_FREE} MB (Free) ${MEM_TOTAL} MB (Total)"
echo " iP Address         : \e[1;32m${IP_LOCAL}\e[00m [ \e[1;33m${IP_EXTERNAL}\e[00m ]"
echo " Load Averages      : ${one}, ${five}, ${fifteen} (1, 5, 15 min)"
echo " Weather            : ${WEATHER_AMBARES}"
echo " Uptime             : ${UPTIME}"
echo " Running Processes  : `ps ax | wc -l | tr -d " "`"
echo " "
