#!/bin/sh

echo " "
echo "Disclaimer: ALL access on that system are monitored. And as such, un-authorized"
echo "attempts to gain access will be procecuted to the full extent of the law."
echo "                                                                          - Alh"
