#!/bin/bash

echo " "
echo "Disclaimer: ALL access on that system are monitored. And as such, un-authorized"
echo "attempts to gain access will be procecuted by the full extent of the law."
echo "                                                                          - Alh"
echo " "

