#        d8888 888 888      
#       d88888 888 888      
#      d88P888 888 888      
#     d88P 888 888 88888b.  
#    d88P  888 888 888 "88b 
#   d88P   888 888 888  888 
#  d8888888888 888 888  888 
# d88P     888 888 888  888    v1.0.18
#
# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = true

# Change the default prompt format
format = """\
[╭╴](238)$env_var$hostname$username$directory\
$all[╰─](238)$shell$status$character"""
# move the rest of the prompt to the right
right_format = """$cmd_duration$time $battery"""
command_timeout = 3_000

# Shows an icon based on the os or distribution
[env_var.STARSHIP_DISTRO]
style = "042"
# - Debian: 160 / Devuan: 093 / Manjaro: 042 / Ubuntu: 208 / Windows: 033
format = '[$env_value]($style) '
variable = "STARSHIP_DISTRO"
disabled = false

# Shows hostname
[hostname]
ssh_only = false
trim_at = "."
format = "[$hostname]($style) "
style = "bold 240"
disabled = false

# Shows the username
[username]
style_user = "bold white"
style_root = "bold red"
format = "[$user]($style) "
show_always = true
disabled = false

# Shows the current directory
[directory]
truncation_length = 20
truncate_to_repo = true
truncation_symbol = " …/"
home_symbol = " ~"
read_only_style = "bold 160"
read_only = " "
format = "[$read_only]($read_only_style)[$path](039) "
disabled = false

# Shows the SHELL indicator
[shell]
style = "white"
zsh_indicator = ""
bash_indicator = ""
powershell_indicator = "PS"
unknown_indicator = "?sh"
disabled = false

# Status
[status]
symbol = " "  # "✗"
success_symbol = "✔️"
not_executable_symbol = "🚫"
not_found_symbol ="🔍"
sigint_symbol = "🧱"
signal_symbol = "⚡"
style = "bold 160"
format = "[$symbol$status]($style) "
recognize_signal_code = true
disabled = false

# Change the default prompt indicator
[character]
# success_symbol = "[ ❯](034)"
# error_symbol = "[❯](250)"
success_symbol = "[](bold 034)[_](bold white)"
error_symbol = "[](bold 160)[_](bold white)"

# Shows Command dureation if > 10s
[cmd_duration]
# Show command execution time over 5 secs (in ms)
min_time = 5_000
format = "Took [$duration]($style)"
disabled = false

# Shows the time
[time]
format = '🕙 [\[$time\]]($style)'
time_format = "%T"
utc_time_offset = "1"
disabled = false

# Shows the battery status 
[battery]
full_symbol = "🔋 "
charging_symbol = "🔌 "
discharging_symbol = " ⚡ "
disabled = false
# "bold red" style when capacity is between 0% and 20%
[[battery.display]]
threshold = 20
style = "bold red"
# "bold orange" style when capacity is between 20% and 40%
[[battery.display]]
threshold = 40
style = "bold orange"
# "bold yellow" style when capacity is between 60% and 100%
[[battery.display]]
threshold = 60
style = "bold yellow"
# "bold green" style when capacity is at 100%
[[battery.display]]
threshold = 100
style = "bold 034"

[memory_usage]
symbol = ""
disabled = true

# Shows the Git branch
[git_branch]
# symbol = " "
symbol = " "
format = "on [$symbol](034) [$branch]($style) "
truncation_length = 15
truncation_symbol = "…/"
style = "bold 034"
disabled = false

# Show the Git status
[git_status]
style = "034"
up_to_date = ""
conflicted = ""
untracked = "${count} "
modified = "${count} "
stashed = "﫻${count} "
renamed = "${count} "  # "  "
deleted = "${count} "
staged = "[$count](034) "
behind = "⇣${count}"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
format = '[\($all_status$ahead_behind\)]($style) '
disabled = false

# Force Python symbol and version
[python]
symbol = ""  # ""
# format = "$symbol"
python_binary = "python3"
disabled = false

# Shows Terraform version
[terraform]
format = "using [ terraform $version]($style) "   # "" 
disabled = false

# Shows Vagrant version
[vagrant]
format = "using [﵂ vagrant $version]($style) "
disabled = false

# Shows Docker context
[docker_context]
format = "using [ $context](bold blue) "
# detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
# only_with_files = true
disabled = false

# Shows Ansible version
# "ﴂ"

# Shows Helm version
[helm]
format = "using [ $version](bold purple) "
disabled = false

# Shows Node.js version
[nodejs]
format = "using [ $version](bold green) "
disabled = true

# Shows Ruby version
[ruby]
format = "using [ $version]($style) "
disabled = false

# Shows AWS context
[aws]
symbol = ""
style = "yellow"
format = 'on [$symbol $profile (\($region\))]($style) '
disabled=true
# Add AWS zone aliases
[aws.region_aliases]
eu-west-3 = "Paris"
us-west-1 = "US, Virginia"

[kubernetes]
format = 'on [☸ $context \($namespace\)](dimmed green) '
disabled = true
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"
